apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{.Values.DEPLOYMENT_NAME}}
  labels:
    app: webapp
spec:
  replicas: {{ .Values.REPLICA_COUNT }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.IMAGE_NAME }}"
          imagePullPolicy: always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
